   name: Daily Dream11 Team Generation
   
   on:
     schedule:
       - cron: '0 13 30 * *'  # Runs at 7 PM IST (adjust based on your timezone)
     workflow_dispatch:  # Allows manual triggering
   
   jobs:
     generate-teams:
       runs-on: ubuntu-latest
       
       steps:
       - name: Checkout repository
         uses: actions/checkout@v3
         
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
           python-version: '3.9'
           
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
           
       - name: Generate Dream11 teams
         run: python ge.py
         
       - name: Upload team logs as artifacts
         uses: actions/upload-artifact@v3
         with:
           name: dream11-teams
           path: team_logs/
           
       - name: Commit and push team logs to repository
         run: |
           git config --global user.name 'GitHub Actions'
           git config --global user.email 'actions@github.com'
           git add team_logs/
           git commit -m "Add Dream11 teams for $(date +'%Y-%m-%d')" || echo "No changes to commit"
           git push
