name: Generate Dream11 Teams

on:
  workflow_dispatch:  # This allows manual triggering only

jobs:
  generate-teams:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install requests pandas numpy beautifulsoup4 scikit-learn
        
    - name: Create directories
      run: |
        mkdir -p logs
        mkdir -p team_logs
        
    - name: Generate Dream11 teams
      run: python3 ge.py
      
    - name: Commit and push team logs
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add team_logs/
        git diff --staged --quiet || git commit -m "Add Dream11 teams for $(date +'%Y-%m-%d')"
        git push origin HEAD:${GITHUB_REF}
